#rest:
#    resource: "@RestBundle/Controller/"
#    type:     annotation
#    prefix:   /

rest_accommodation:
    type:     rest
    resource: Dizda\RestBundle\Controller\AccommodationController
    prefix:   /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

crawler:
    resource: "@CrawlerBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

